"""
Structured Personas for LLM Happiness Survey (Fourth Approach)

Personas include all information from the long-text personas in personas.py,
as structured fields. Nationality is the main focus. Half male, half female.
List order is shuffled (fixed permutation for reproducibility).
"""

import random

# Full structured personas (all info from long text). Ids 1-10 male, 11-20 female.
_PERSONAS_UNSHUFFLED = [
    {
        "id": 1,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 28,
        "job": "software engineer",
        "work_details": "Works at a tech startup in a major city. Been in current city 5 years, settled in career.",
        "living_situation": "Lives alone in a small apartment.",
        "family": "Family lives in a different city; maintains contact via video calls and holiday visits.",
        "hobbies": "Coding, video games, weekend hiking in nature reserves, board game nights with university friends.",
        "values_or_notes": "Values work-life balance, independence. Passionate about technology and industry trends.",
    },
    {
        "id": 2,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 45,
        "job": "primary school teacher",
        "work_details": "Teaching 20 years at the same elementary school. Passionate about education and students' achievements.",
        "living_situation": "House with backyard.",
        "family": "Married with two teenage children; busy with school activities and sports.",
        "hobbies": "Reading historical novels, gardening, volunteering at local community center on weekends.",
        "values_or_notes": "Deep roots in community, knows many families through teaching. Values stability and routine.",
    },
    {
        "id": 3,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 22,
        "job": "university student (economics)",
        "work_details": "Part-time at a coffee shop, evening shifts after classes. Planning master's degree, researching programs.",
        "living_situation": "Shared apartment with three roommates.",
        "family": "Independent; family elsewhere.",
        "hobbies": "Debate club, discussing politics and economics with friends, concerts, city nightlife.",
        "values_or_notes": "Worries about student debt but optimistic about career. Active in student organizations.",
    },
    {
        "id": 4,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 55,
        "job": "retired nurse",
        "work_details": "Retired; now spends most time caring for elderly parents who live nearby.",
        "living_situation": "Same neighborhood for 30 years; knows all neighbors.",
        "family": "Three adult children in different cities; weekly phone calls and occasional visits. Has grandchildren.",
        "hobbies": "Cooking traditional family recipes, knitting for grandchildren, weekly book club at library, gardening with vegetable patch.",
        "values_or_notes": "Finds purpose in helping others. Sometimes misses nursing career but appreciates time for family.",
    },
    {
        "id": 5,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 35,
        "job": "small business owner (bakery)",
        "work_details": "Local bakery, 8 years in operation. Wakes at 4 AM for fresh bread and pastries; long hours. Family traditional recipes.",
        "living_situation": "Family home.",
        "family": "Married to a teacher; one child age 6 who sometimes helps in bakery on weekends.",
        "hobbies": "Cooking at home, watching cooking shows when possible.",
        "values_or_notes": "Loves work and customer connection; finds it physically demanding. Worries about competition from chain stores. Sometimes overwhelmed.",
    },
    {
        "id": 6,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 19,
        "job": "delivery driver",
        "work_details": "Food delivery service. Flexible hours. Saving money to travel.",
        "living_situation": "Lives with parents and two younger siblings in a modest home; contributes to household expenses.",
        "family": "Parents and two younger siblings.",
        "hobbies": "Soccer with friends on weekends, movies, social media.",
        "values_or_notes": "Dreams of studying abroad (Europe or Asia). Pressure from family on career path but wants to explore. Appreciates current freedom.",
    },
    {
        "id": 7,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 50,
        "job": "construction worker",
        "work_details": "25 years in industry, various building projects. Long hours outdoors in all weather; toll on body. Values job security and camaraderie with coworkers.",
        "living_situation": "Own place.",
        "family": "Divorced; joint custody of two children ages 12 and 15; sees them every other weekend and holidays.",
        "hobbies": "Fishing at nearby lake, watching sports on TV, barbecues with neighbors.",
        "values_or_notes": "Appreciates job stability and supporting children. Worries about finding lighter work as he gets older.",
    },
    {
        "id": 8,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 32,
        "job": "marketing manager",
        "work_details": "Multinational corporation; digital marketing campaigns across several countries. Travels about one week per month; finds it exciting but exhausting. Works late, takes online courses.",
        "living_situation": "Single; lives alone in modern apartment in city center.",
        "family": "Single; no children.",
        "hobbies": "Fitness, new restaurants, art exhibitions, concerts, active social life.",
        "values_or_notes": "Values career advancement and personal growth. Sometimes feels lonely despite busy schedule; appreciates independence.",
    },
    {
        "id": 9,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 67,
        "job": "retired factory worker",
        "work_details": "Manufacturing 40 years; retired 2 years ago.",
        "living_situation": "Long-term home; neighbors nearby.",
        "family": "Married 45 years to high school sweetheart. Four children all within driving distance. Five grandchildren; picks them up from school, helps with homework.",
        "hobbies": "Chess in the park with other retirees, TV and news, sharing stories with neighbors on front porch.",
        "values_or_notes": "Witnessed many changes over decades; sometimes nostalgic. Values family above all; joy in family gatherings and traditions. Worries about health but tries to stay active.",
    },
    {
        "id": 10,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 26,
        "job": "freelance graphic designer",
        "work_details": "Works from home; logos, websites, marketing materials. Irregular income, month-to-month fluctuation. Sets own schedule.",
        "living_situation": "Lives with partner (works in retail). Has a cat.",
        "family": "Partner; no children.",
        "hobbies": "Art, museums and galleries, music festivals in summer, exploring new neighborhoods.",
        "values_or_notes": "Enjoys flexibility and creative freedom. Sometimes struggles with isolation and uncertainty. Dreams of own design studio.",
    },
    {
        "id": 11,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 40,
        "job": "doctor",
        "work_details": "Public hospital emergency department; life-and-death situations daily. 12-hour shifts, often overnight; disrupts sleep and family life.",
        "living_situation": "Family home.",
        "family": "Married to another doctor (different hospital). Two young children ages 5 and 8; sees them less than she would like.",
        "hobbies": "Medical journals, playing piano to relax, running to manage stress.",
        "values_or_notes": "Struggles with work-family balance; guilt about missing school events or family dinners. Committed to helping others; emotional toll significant. Worries about burnout.",
    },
    {
        "id": 12,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 29,
        "job": "stay-at-home parent",
        "work_details": "Left job in finance 3 years ago to care for children. May return part-time when children start school.",
        "living_situation": "Family home with partner and children.",
        "family": "Two toddlers ages 2 and 4; constant attention and care. Supportive partner. Good network of parent friends.",
        "hobbies": "Playdates at local park, storytime at library, organizing activities at home.",
        "values_or_notes": "Sometimes misses career and adult conversation; values time with children and finds fulfillment in raising them. Struggles with monotony and sometimes isolation.",
    },
    {
        "id": 13,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 38,
        "job": "taxi driver",
        "work_details": "Driving 15 years; primarily night shifts 6 PM–2 AM. Knows city streets well; pride in fastest routes.",
        "living_situation": "Family home.",
        "family": "Married to a nurse (day shifts); see each other mainly on weekends. One child age 10; helps with homework in mornings.",
        "hobbies": "Music and podcasts while driving. Family time on days off: movies, family dinners.",
        "values_or_notes": "Meets many people; enjoys conversations. Appreciates job flexibility. Worries about physical toll of sitting long hours.",
    },
    {
        "id": 14,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 24,
        "job": "research assistant",
        "work_details": "University; data analysis and literature reviews for a professor. Environmental science. Hopes to pursue PhD in next year or two.",
        "living_situation": "Small studio apartment near university; budgets carefully, simple meals, limited entertainment.",
        "family": "Independent.",
        "hobbies": "Academic conferences, coffee shops reading and writing, environmental activism groups.",
        "values_or_notes": "Passionate about field. Excited about career and contributing to research. Sometimes overwhelmed by competitive academic environment. Values intellectual stimulation and meaningful work over financial gain.",
    },
    {
        "id": 15,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 60,
        "job": "farmer",
        "work_details": "40 years on the land. Family farm passed down generations; vegetables and some livestock. Dawn to long hours in all weather. Sells via farmers markets and local stores.",
        "living_situation": "Family farm; countryside.",
        "family": "Married to another farmer. Three adult children; two help with farm, one works in city.",
        "hobbies": "Connection to nature, changing seasons, satisfaction of providing food for community.",
        "values_or_notes": "Great pride in work and produce quality. Worries about climate change and future of small family farms. Finds peace in rhythm of farm work and countryside.",
    },
    {
        "id": 16,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 31,
        "job": "social worker",
        "work_details": "Helps families in need; poverty, domestic violence, substance abuse. Long hours; sometimes takes work home; struggles with boundaries. Emotionally challenging but rewarding when making a difference.",
        "living_situation": "Single; lives alone in small apartment; quiet space to decompress.",
        "family": "Single; no children.",
        "hobbies": "Yoga and meditation, close friends who understand her work, reading fiction to escape.",
        "values_or_notes": "Dedicated to making a difference; believes in social justice. Sometimes burned out but committed to career and people she serves.",
    },
    {
        "id": 17,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 18,
        "job": "high school student",
        "work_details": "Final year; preparing intensively for university entrance exams. Long study hours, extra tutoring, practice exams.",
        "living_situation": "Lives with parents and younger sibling in suburban home.",
        "family": "Parents and younger sibling.",
        "hobbies": "Video games and friends when rare free time.",
        "values_or_notes": "Significant pressure from parents, teachers, self. Anxious about future and career path. Feels missing out on typical teenage experiences but believes sacrifice worth it. Dreams of more freedom at university.",
    },
    {
        "id": 18,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 48,
        "job": "restaurant manager",
        "work_details": "Busy establishment; lunch and dinner, hundreds of customers daily. Evenings and weekends; often home after spouse and children asleep.",
        "living_situation": "Family home.",
        "family": "Married to an accountant. One teenager becoming more independent.",
        "hobbies": "Cooking at home on rare days off, new recipes, cooking shows for inspiration.",
        "values_or_notes": "Pride in restaurant reputation and team. Long hours and pressure exhausting. Values good service and positive dining experience. Dreams of own smaller restaurant with more reasonable hours; financial risk daunting.",
    },
    {
        "id": 19,
        "nationality": "{nationality}",
        "gender": "female",
        "age": 36,
        "job": "architect",
        "work_details": "Sustainable building projects; energy-efficient homes and commercial buildings. Medium-sized firm; several award-winning projects. Environmental design and urban planning.",
        "living_situation": "Own place.",
        "family": "Long-term relationship with graphic designer; not married; focusing on careers and personal growth.",
        "hobbies": "Cycling to work, art galleries and architectural exhibitions, traveling to see buildings and urban design worldwide.",
        "values_or_notes": "Believes better architecture can improve lives and address climate change. Sometimes struggles with slow pace of change in construction; remains optimistic about sustainable design.",
    },
    {
        "id": 20,
        "nationality": "{nationality}",
        "gender": "male",
        "age": 42,
        "job": "unemployed",
        "work_details": "Lost job in manufacturing 6 months ago; factory closed after 15 years, moved overseas. Actively searching; multiple applications weekly; difficult to find matching skills and living wage. Job fairs, online applications. Willing to retrain.",
        "living_situation": "Family home with spouse and children.",
        "family": "Married to retail worker. Two school-age children ages 9 and 12; worries about providing for them.",
        "hobbies": "Household tasks and childcare while searching.",
        "values_or_notes": "Worries constantly about finances, future, supporting family. Loss of identity and self-worth; job application rejections demoralizing. Uncertainty stressful for whole family.",
    },
]

# Shuffle with fixed seed so order is reproducible (same permutation every time).
_random = random.Random(42)
_ORDER = list(range(len(_PERSONAS_UNSHUFFLED)))
_random.shuffle(_ORDER)

STRUCTURED_PERSONAS = [_PERSONAS_UNSHUFFLED[i] for i in _ORDER]


def get_structured_persona(persona_id):
    """Return the structured persona with the given id, or None."""
    for p in STRUCTURED_PERSONAS:
        if p["id"] == persona_id:
            return p
    return None


def get_all_structured_personas():
    """Return all 20 structured personas in shuffled order (10 male, 10 female)."""
    return list(STRUCTURED_PERSONAS)
